Atualização do arquivo modman
pedro-teixeira/correios pull request #408
Opened 2019-01-29 23:50 UTC by marcussucupira

A pasta lib não estava no lugar certo, gerando problemas com o rastreamento de encomendas.
Utilizei o script generate-modman

2019-02-05 07:30 UTC, pedro-teixeira requested changes

2019-02-05 07:30 UTC, pedro-teixeira commented on modman
> +lib/Correios/Rastro.php            lib/Correios/Rastro.php
@marcussucupira não faz mais sentido `lib/Correios      lib/Correios` para copiar a pasta inteira? Pode testar se funciona?

2019-02-06 14:11 UTC, marcussucupira commented on modman
> +lib/Correios/Rastro.php            lib/Correios/Rastro.php
Não vejo problemas.

2019-02-07 18:19 UTC, pedro-teixeira requested changes

2019-02-07 18:19 UTC, pedro-teixeira commented on modman
> +lib/Correios/Rastro.php            lib/Correios/Rastro.php
Fico esperando a mudança da PR para aprovar.

2019-02-08 19:24 UTC, pedro-teixeira commented
Duplicated.

2019-02-08 19:24 UTC, closed without merging